version 7.2

" load all files in ~/.vim/0-my_stuff/
" thx @ http://stackoverflow.com/a/14508800 and
" http://learnvimscriptthehardway.stevelosh.com/chapters/40.html
for f in split(globpath('~/.vim/0-my_stuff/', '*'), '\n')
  execute 'source '.fnameescape(f)
endfor

augroup filetypedetect
    au BufRead,BufNewFile *.sls setfiletype sls
augroup END

call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-plug'  " plug help
Plug 'felixhummel/sahara'  " color scheme
Plug 'editorconfig/editorconfig-vim'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'  " default snippets
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'leshill/vim-json'
Plug 'saltstack/salt-vim'
Plug 'stephpy/vim-yaml'
Plug 'lepture/vim-jinja'
Plug 'chr4/nginx.vim'
Plug 'chr4/sslsecure.vim'
Plug 'robbles/logstash.vim'
Plug 'tpope/vim-commentary'
Plug 'hashivim/vim-terraform'
" Plug 'vim-syntastic/syntastic'
Plug 'juliosueiras/vim-terraform-completion'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'davidhalter/jedi-vim', { 'for': 'python' }
call plug#end()

set background=dark
set backspace=indent,eol,start
set fileencodings=utf-8,ucs-bom,default,latin1
set helplang=en
set history=9000
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set termencoding=utf-8
set viminfo='20,\"50
set wildignore=*.pyc,*.egg-info/
set modeline  " execute custom modelines in files
set laststatus=2  " always display status line
set mouse-=a  " disable mouse
set hlsearch  " highlight all search terms
set wildmode=longest:list  " bash-like tab completion
set tabpagemax=99  " give me many tabs (not just 10 of them)
set tabstop=2  " see :retab
set softtabstop=2  " compatability with mix of tabs and spaces
set shiftwidth=2  " for >> and <<
set iskeyword+=-

" persistent undo
set undofile
set undodir=~/.vim/undodir

" completion
set complete=.,w,b,u,t
set noswapfile  " disable swapfiles

" NERDTree
let g:NERDTreeWinPos="right"
let NERDTreeShowHidden=1
map <F10> :NERDTreeToggle<CR>
" http://stackoverflow.com/questions/1447334/how-do-you-add-nerdtree-to-your-vimrc
"autocmd VimEnter * NERDTree
"autocmd VimEnter * wincmd p

silent! colorscheme sahara

let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips', 'UltiSnips']

" default to bash
" see :help ft-bash-syntax
let g:is_bash	= 1

augroup felix
  " Jump to last cursor position unless it's invalid or in an event handler
  " https://github.com/garybernhardt/dotfiles/blob/master/.vimrc
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif
  " except git commit messages
  " https://stackoverflow.com/a/2397507
  autocmd BufReadPost COMMIT_EDITMSG
    \ exe "normal! gg"
augroup END

" vim: set ft=vim 

let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

" don't complete on every dot entered (keep fast pasting in insert mode)
let g:jedi#popup_on_dot = 0
let g:jedi#show_call_signatures = 0
