#!/bin/bash
# shellcheck disable=SC2034,SC2086

# https://github.com/termstandard/colors#terminal-colors
# https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh
_color_hex2rgb() {
    rgb=$1
    echo "$((16#${rgb:0:2}));$((16#${rgb:2:2}));$((16#${rgb:4:2}))"
}
_color_bg() {
    hexs=$(_color_hex2rgb $1)
    echo "\[\e[48;2;${hexs}m\]"
}
_color_fg() {
    hexs=$(_color_hex2rgb $1)
    echo "\[\e[38;2;${hexs}m\]"
}
_color() {
    echo "$(_color_fg $1)$(_color_bg $2)"
}

_COLOR_CLEAR="\[\e[0m\]"
_COLOR_GOLD="\[\e[38;5;136m\]"
_COLOR_GREEN="\[\e[0;32m\]"
_COLOR_RED="\[\e[0;31m\]"
_COLOR_LO="$(_color 00aa00 002000)"
_COLOR_ME="$(_color dd0000 260e00)"
_COLOR_HI="$(_color ff0000 330000)"
_COLOR_RET_ERR="$_COLOR_RED"
