#!/bin/bash
if [[ -d $HOME/go ]]; then
  export GOPATH=$HOME/go
  export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
  if [[ -f ~/go/bin/gocomplete ]]; then
    complete -C $HOME/go/bin/gocomplete go
  fi
fi

