#!/bin/bash
# http://bitmote.com/index.php?post/2012/11/19/Using-ANSI-Color-Codes-to-Colorize-Your-Bash-Prompt-on-Linux
# tested with DejaVu Sans Mono Book 11 on 27" at 1920x1080

# https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg
ansi256() {
    local num=$1
    echo -e "\[\e[38;5;${num}m\]"
}

# some color definitions
CLEAR="\[\e[0m\]"
BLACK="\[\e[0;30m\]"
RED="\[\e[0;31m\]"
GREEN="\[\e[0;32m\]"
BROWN="\[\e[0;33m\]"
BLUE="\[\e[0;34m\]"
PURPLE="\[\e[0;35m\]"
CYAN="\[\e[0;36m\]"
LIGHT_GRAY="\[\e[0;37m\]"
DARK_GRAY="\[\e[1;30m\]"
LIGHT_RED="\[\e[1;31m\]"
LIGHT_GREEN="\[\e[1;32m\]"
YELLOW="\[\e[1;33m\]"
LIGHT_BLUE="\[\e[1;34m\]"
LIGHT_PURPLE="\[\e[1;35m\]"
LIGHT_CYAN="\[\e[1;36m\]"
WHITE="\[\e[1;37m\]"
GOLD="\[\e[38;5;136m\]"

git_prompt() {
    local retcode=$?  # this must be first

    # user@host
    host_color=$GOLD
    host_prefix="\u@${host_color}\h"

    # check for git
    local x=""
    status=$(git status -s 2>/dev/null)  # 4 ms on my box, recurses automatically
    if [[ $? == 0 ]]; then
        # in a git repository
        branch=$(git branch | grep ^* | sed s/\*\ //)
        [[ -z $branch ]] && branch='[NOBRANCH]'
        branch_color="${PURPLE}"
        if [[ -z $status ]]; then
            branch_color="${GREEN}"
        else
            branch_color="${RED}"
        fi
        git_stuff=" $branch_color${branch}"
    else
        git_stuff=""
    fi

    # working directory
    local dir=" ${GREEN}\w"

    # non-zero exit
    local exit_part=''
    local uid_color="${CLEAR}"
    if [[ $retcode != 0 ]]; then
        uid_color="${RED}"
    fi
    uid="${uid_color}\\\$${CLEAR}"

    # check for venv
    [[ -n $VIRTUAL_ENV || $VIRTUAL_ENV == ' ' ]] && venv="${WHITE}venv${CLEAR} "

    # 2-row inspired by simonswine https://asciinema.org/a/47444
    # putting it all together
    indicator="${GOLD}▶▶▶${CLEAR}"
    line1="$indicator $venv$host_prefix$git_stuff$dir ${CLEAR}"
    line2="$uid "
    x="$line1\n$line2"

    PS1=$x
}

PROMPT_COMMAND=git_prompt

# TODO find out why xfce4-terminal fails to render
#   "${LIGHT_PURPLE}+ ${CLEAR}"
export PS4="▬ "

# debug
# http://stackoverflow.com/questions/5014823/how-to-profile-a-bash-shell-script-slow-startup
#export PS4="▬ $(date "+.%N")\011 "

# vim: set ft=sh :

