#!/bin/bash
# shellcheck disable=SC2034

# some color definitions
CLEAR="\[\e[0m\]"
BLACK="\[\e[0;30m\]"
RED="\[\e[0;31m\]"
GREEN="\[\e[0;32m\]"
BROWN="\[\e[0;33m\]"
BLUE="\[\e[0;34m\]"
PURPLE="\[\e[0;35m\]"
CYAN="\[\e[0;36m\]"
LIGHT_GRAY="\[\e[0;37m\]"
DARK_GRAY="\[\e[1;30m\]"
LIGHT_RED="\[\e[1;31m\]"
LIGHT_GREEN="\[\e[1;32m\]"
YELLOW="\[\e[1;33m\]"
LIGHT_BLUE="\[\e[1;34m\]"
LIGHT_PURPLE="\[\e[1;35m\]"
LIGHT_CYAN="\[\e[1;36m\]"
WHITE="\[\e[1;37m\]"
GOLD="\[\e[38;5;136m\]"

__fh_prompt_git_stuff() {
    local branch
    local branch_color
    local git_status
    # ignore $HOME
    [[ $PWD == $HOME ]] && return
    # check if we're in a git repo
    # 4 ms on my box, recurses automatically
    git_status=$(git status -s 2>/dev/null)
    if [[ $? != 0 ]]; then
        return
    else
        branch=$(git branch | grep '^*' | sed s/\*\ //)
        [[ -z $branch ]] && branch='[NOBRANCH]'
        if [[ -z $git_status ]]; then
            branch_color="${GREEN}"
        else
            branch_color="${RED}"
        fi
        echo " ${branch_color}${branch}"
    fi
}

__fh_prompt_terraform() {
    local tf_env_file=$PWD/.terraform/environment
    [[ -f $tf_env_file ]] && echo " $GOLD[$(<$tf_env_file)]"
}

__fh_prompt() {
    local retcode=$?  # this must be first

    # user@host
    local host_color=$GOLD
    local host_prefix="\u@${host_color}\h"

    # working directory
    local dir=" ${GREEN}\w"

    # non-zero exit
    local exit_part=''
    local uid_color="${GOLD}"
    if [[ $retcode != 0 ]]; then
        uid_color="${RED}"
    fi
    local uid=" ${uid_color}\\\$"

    # putting it all together
    PS1="${host_prefix}$(__fh_prompt_git_stuff)$(__fh_prompt_terraform)${dir}${uid} ${CLEAR}"

    # always append history
    history -a
}

PROMPT_COMMAND=__fh_prompt

# TODO find out why xfce4-terminal fails to render
#   "${LIGHT_PURPLE}+ ${CLEAR}"
export PS4="▬ "

# debug
# http://stackoverflow.com/questions/5014823/how-to-profile-a-bash-shell-script-slow-startup
# export PS4='▬ $(date "+.%N")\011 '
# source prompt

# vim: set ft=sh :
