#!/bin/bash

# some color definitions
BLACK="\[\e[0;30m\]"
RED="\[\e[0;31m\]"
GREEN="\[\e[0;32m\]"
BROWN="\[\e[0;33m\]"
BLUE="\[\e[0;34m\]"
PURPLE="\[\e[0;35m\]"
CYAN="\[\e[0;36m\]"
LIGHT_GRAY="\[\e[0;37m\]"
DARK_GRAY="\[\e[1;30m\]"
LIGHT_RED="\[\e[1;31m\]"
LIGHT_GREEN="\[\e[1;32m\]"
YELLOW="\[\e[1;33m\]"
LIGHT_BLUE="\[\e[1;34m\]"
LIGHT_PURPLE="\[\e[1;35m\]"
LIGHT_CYAN="\[\e[1;36m\]"
WHITE="\[\e[1;37m\]"
NOTHING="\[\e[0m\]"

host_prefix="\u@\h"
host_color=${LIGHT_GRAY}
default_prompt="${VENV_FLAG}${host_color}$host_prefix ${GREEN}\w ${LIGHT_GREEN}\\\$${NOTHING} "

git_prompt() {
    # check for git
    local x=""
    status=$(git status -s 2>/dev/null)  # 4 ms on my box, recurses automatically
    if [[ $? != 0 ]]; then
        # not in a git repository
        x=$default_prompt
    else
        # in a git repository
        branch=$(git branch | grep ^* | sed s/\*\ //)
        [[ -z $branch ]] && branch='[NOBRANCH]'
        branch_color="${PURPLE}"
        if [[ -z $status ]]; then
            branch_color="${GREEN}"
        else
            branch_color="${RED}"
        fi
        x="$host_prefix $branch_color${branch} ${GREEN}\w ${LIGHT_GREEN}\\$ ${NOTHING}"
    fi

    # check for venv
    [[ -n $VIRTUAL_ENV || $VIRTUAL_ENV == ' ' ]] && x="${WHITE}venv${NOTHING} $x"

    PS1=$x
}

PROMPT_COMMAND=git_prompt

export PS4="${LIGHT_PURPLE}+ ${NOTHING}"

# vim: set ft=sh :
