#!/bin/bash

PYENV_ROOT="$HOME/.pyenv"

if [[ -d $PYENV_ROOT ]]; then
  export PYENV_ROOT
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
  export PYENV_VIRTUALENV_DISABLE_PROMPT=1
fi

my_pyenv_bin=$PYENV_ROOT/versions/$USER/bin

if [[ -d $my_pyenv_bin ]]; then
  pyenv global $USER
fi
