#!/bin/bash
# shellcheck disable=SC1090,SC2086,SC2231

# FH_BASH_PROFILE=1 bash -xic echo 2> ~/profile-bash.log
[[ ${FH_BASH_PROFILE:-0} != 0 ]] && export PS4='▬ $(date "+%s.%N")\011 '
# include binaries from $HOME/bin.
# $HOME/.bin contains stuff I don't want to publish (yet)
export PATH=$HOME/.bin:$HOME/bin:$PATH:$HOME/.local/bin

# set vim as default editor
vim=/usr/bin/vim
export EDITOR=$vim
export VISUAL=$vim

# tweak history
export HISTTIMEFORMAT='%F__%H-%M-%S $ '
export HISTCONTROL=ignoreboth
# if a line has ~100 chars (each 1 byte usually, because utf-8) then 10 lines = 1k
# max 100 MB --> 100 * 10.000 = 1.000.000 lines
export HISTSIZE=1000000
# two lines per hist (timestamp, command) --> 2.000.000 lines
export HISTFILESIZE=2000000
export HISTIGNORE="ls:la:l:pwd:clear:history:jobs:fg:bg:pushd*:popd*:g s:g d:g l"

# https://lobste.rs/s/lrx8vc/assorted_less_1_tips
export LESS='-Ri -x4 --use-color'

# use custom manpage section "f"
export MANSECT="1:n:l:8:3:2:3posix:3pm:3perl:3am:5:4:9:6:7:f"

# ignore when completing
export FIGNORE=".egg-info:Cargo.lock:$FIGNORE"

# if we're non-interactive, then we're done
# =========================================
[[ -z $PS1 ]] >&2 && return
# =========================================

# global bash completion
[[ -s /etc/bash_completion ]] && source /etc/bash_completion

# load everything from $HOME/.bash/ except README.md and directories
if [[ -d $HOME/.bash/ ]]; then
  for f in $HOME/.bash/*; do
    [[ $f == *README.md* ]] && continue
    [[ -d $f ]] && continue
    source $f
  done
fi

# also load local stuff
if compgen -G "$HOME/.bash.local/*.sh" >/dev/null; then
  for f in $HOME/.bash.local/*.sh; do
    mode=$(stat -c %a $f)
    if [[ $mode != 600 ]]; then
      echo "WARNING $f has mode $mode. Fix: chmod 600 $f" >&2
    fi
    source $f
  done
fi
