# include binaries from $HOME/bin. To add more, link them in $HOME/bin/
# $HOME/bin.private contains stuff I don't want to publish (yet)
export PATH=$HOME/bin.private:$HOME/bin:$PATH:$HOME/.local/bin

[[ -d /usr/local/go/bin ]] && export PATH=$PATH:/usr/local/go/bin

# set vim as default editor
vim=/usr/bin/vim
export EDITOR=$vim
export VISUAL=$vim

# global bash completion
[[ -s /etc/bash_completion ]] && source /etc/bash_completion

# tweak history
export HISTTIMEFORMAT='%F__%H-%M-%S '
export HISTCONTROL=ignoreboth
# if a line has ~100 chars (each 1 byte usually, because utf-8) then 10 lines = 1k
# max 100 MB --> 100 * 10.000 = 1.000.000 lines
export HISTSIZE=1000000
# two lines per hist (timestamp, command) --> 2.000.000 lines
export HISTFILESIZE=2000000
export HISTIGNORE="ls:la:l:cd:pwd:clear:history:jobs:fg:bg:pushd*:popd*:g s:g d:g l"

# https://github.com/rcaloras/bash-preexec/
source ~/.bash-preexec.sh

# load everything from $HOME/.bash/ except README.md and directories
if [[ -d $HOME/.bash/ ]]; then
    for f in $HOME/.bash/*; do
        [[ $f == *README.md* ]] && continue
        [[ -d $f ]] && continue
        source $f
    done
fi

# also load local stuff
if [[ -z $HOME/.bash.local/*.sh ]]; then
  for f in $HOME/.bash.local/*.sh; do
    mode=$(stat -c %a $f)
    if [[ $mode != 600 ]]; then
      echo "WARNING $f has mode $mode" >&2
    fi
    source $f
  done
fi

